Repository AY2425S1-CS2103T-W09-2/tp, pull requests merged in 2024-10, with the labels that each got.

#19 Add Josh's image and description to aboutus
  docs/AboutUs.md
Labels: priority.Medium

#22 Update aboutus
  docs/AboutUs.md
  docs/images/johndoe.png
  docs/images/timenikhil.png
Labels: priority.High

#23 Update kimxw.md and AboutUs.md
  docs/AboutUs.md
  docs/images/kimxw.png
  docs/team/kimxw.md
Labels: priority.High

#28 Tutorial adding command
  docs/AboutUs.md
  docs/images/kimxw.png
  docs/team/kimxw.md
Labels: priority.High

#25 Switch theme from minima to Cayman
  docs/_config.yml
Labels: severity.VeryLow, priority.Medium

#33 Update aboutus
  docs/AboutUs.md
  docs/team/timenikhil.md
Labels: severity.High, priority.High

#34 Update _config.yml to change name to EduLog
  docs/_config.yml
Labels: severity.High, priority.Low

#55 Update role
  docs/AboutUs.md
Labels: type.Bug, priority.High

#51 Update README.md to fix CI badge
  README.md
Labels: priority.Medium, type.Documentation

#52 Update README.md to acknowledge AB3
  README.md
Labels: severity.Medium, priority.Medium

#59 Add NFR and Glossary to DG
  docs/DeveloperGuide.md
  docs/team/obrona.md
Labels: priority.High, type.Documentation

#61 Add use cases
  docs/DeveloperGuide.md
Labels: priority.High

#66 DG: Product Scope formatting changes
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#65 Fix: Portfolio markdown and src images in AboutUs
  docs/AboutUs.md
  docs/team/josh1248.md
  docs/team/nathanshew.md
Labels: priority.High, type.Documentation

#85 Add LessonCard and LessonListPael UI components
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/java/seedu/address/ui/LessonListPanel.java
  src/main/resources/view/LessonListCard.fxml
  src/main/resources/view/LessonListPanel.fxml
  src/test/java/seedu/address/model/calendar/StartDateTest.java
  src/test/java/seedu/address/model/calendar/endTimeTest.java
  src/test/java/seedu/address/model/calendar/startTimeTest.java
Labels: priority.High

#86 Add Delete Lesson
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/calendar/EdulogCalendar.java
  src/main/java/seedu/address/model/calendar/Lesson.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#106 Fix Configuration
  build.gradle
  src/main/java/seedu/edulog/storage/JsonAdaptedStudent.java
Labels: type.Bug, severity.High, priority.High

#133 Add MarkAllCommand
  src/main/java/seedu/edulog/logic/commands/MarkAllCommand.java
  src/main/java/seedu/edulog/logic/parser/EduLogParser.java
  src/main/java/seedu/edulog/model/EduLog.java
  src/main/java/seedu/edulog/model/Model.java
  src/main/java/seedu/edulog/model/ModelManager.java
  src/test/java/seedu/edulog/logic/commands/AddCommandTest.java
  src/test/java/seedu/edulog/logic/commands/MarkAllTest.java
Labels: priority.High

#135 Switch docs markbind
  .github/workflows/docs.yml
  .gitignore
  docs/.gitignore
  docs/AboutUs.md
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Gemfile
  docs/Gemfile.lock
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_data/projects.yml
  docs/_includes/custom-head.html
  docs/_includes/head.html
  docs/_includes/header.html
  docs/_layouts/alt-page.html
  docs/_layouts/default.html
  docs/_layouts/page.html
  docs/_markbind/layouts/default.md
  docs/_markbind/variables.json
  docs/_markbind/variables.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-mixins.scss
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
  docs/_sass/minima/initialize.scss
  docs/_sass/minima/skins/classic.scss
  docs/_sass/minima/skins/solarized-dark.scss
  docs/_sass/minima/skins/solarized.scss
  docs/assets/css/style.scss
  docs/index.md
  docs/package-lock.json
  docs/package.json
  docs/site.json
  docs/stylesheets/main.css
  docs/team/josh1248.md
  docs/team/kimxw.md
  docs/team/nathanshew.md
  docs/team/obrona.md
  docs/team/timenikhil.md
Labels: severity.Low, priority.High, type.Documentation

#137 Change to paid
  docs/UserGuide.md
  src/main/java/seedu/edulog/logic/commands/MarkAllCommand.java
  src/main/java/seedu/edulog/logic/commands/MarkCommand.java
  src/main/java/seedu/edulog/logic/commands/MarkIndexCommand.java
  src/main/java/seedu/edulog/logic/commands/UnmarkAllCommand.java
  src/main/java/seedu/edulog/logic/commands/UnmarkCommand.java
  src/main/java/seedu/edulog/logic/commands/UnmarkIndexCommand.java
  src/main/java/seedu/edulog/logic/commands/UnmarkNameCommand.java
  src/main/java/seedu/edulog/model/EduLog.java
  src/main/java/seedu/edulog/model/Model.java
  src/main/java/seedu/edulog/model/ModelManager.java
  src/main/java/seedu/edulog/model/student/Student.java
  src/test/java/seedu/edulog/model/student/StudentTest.java
  src/test/java/seedu/edulog/testutil/StudentBuilder.java
Labels: priority.High

#138 User guide update
  docs/UserGuide.md
Labels: severity.High, priority.High, type.Documentation

#140 Payment UI
  src/main/java/seedu/edulog/ui/StudentCard.java
  src/main/resources/images/paid.png
  src/main/resources/images/unpaid.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
Labels: priority.High

#144 Fix Mark Command
  docs/images/Ui.png
  src/main/java/seedu/edulog/model/EduLog.java
  src/main/java/seedu/edulog/model/student/Student.java
  src/main/java/seedu/edulog/model/util/SampleDataUtil.java
  src/main/java/seedu/edulog/ui/StudentCard.java
Labels: type.Bug, severity.High, priority.High

#147 enable assertions in build.gradle
  build.gradle
Labels: type.Bug, severity.High, priority.High

#149 UML changes for UI and Assertions in LessonListPanel
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/edulog/ui/LessonListPanel.java
  src/main/java/seedu/edulog/ui/StudentCard.java
Labels: priority.High

#150 Update UML for storage classes
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Documentation
