Repository AY2425S1-CS2103T-W09-2/tp, pull requests merged in 2024-11, with the labels that each got.

#169 Fix fee alpha bugs
  src/main/java/seedu/edulog/model/student/Fee.java
  src/test/java/seedu/edulog/model/student/FeeTest.java
Labels: priority.High, alpha-bug

#178 Refactor and Test Fixes for RevenueCommand
  src/main/java/seedu/edulog/logic/commands/PaidRevenueCommand.java
  src/main/java/seedu/edulog/logic/commands/RevenueCommand.java
  src/main/java/seedu/edulog/logic/commands/UnpaidRevenueCommand.java
  src/main/java/seedu/edulog/logic/parser/RevenueCommandParser.java
  src/main/java/seedu/edulog/model/Model.java
  src/test/java/seedu/edulog/logic/commands/RevenueCommandTest.java
  src/test/java/seedu/edulog/logic/parser/RevenueCommandParserTest.java
Labels: priority.High

#184 Update UG for revenue command
  docs/UserGuide.md
Labels: type.Documentation

#176 Resolve alpha bugs
  src/main/java/seedu/edulog/logic/commands/AddLessonCommand.java
  src/main/java/seedu/edulog/logic/commands/DeleteLessonCommand.java
Labels: alpha-bug

#201 Update DG for Revenue use case
  docs/DeveloperGuide.md
Labels: priority.High

#212 Add UC11, UC12
  docs/DeveloperGuide.md
Labels: priority.Low, type.Documentation

#285 Fix clear command for lesson calendar and fix UG
  docs/UserGuide.md
  docs/images/Edulog.png
  docs/images/IdeaIcon.png
  docs/images/InfoIcon.png
  docs/images/demos/calendarCommands/addLesson.png
  docs/images/demos/calendarCommands/collatedCommands.png
  docs/images/demos/calendarCommands/deleteLesson.png
  docs/images/demos/calendarCommands/displayCalendar.png
  docs/images/demos/giftCommands/collatedCommands.png
  docs/images/demos/giftCommands/giftCommand.png
  docs/images/demos/revenueCommands/collatedCommands.png
  docs/images/demos/revenueCommands/markByIndex.png
  docs/images/demos/revenueCommands/markall.png
  docs/images/demos/revenueCommands/revenuePaid.png
  docs/images/demos/revenueCommands/revenueUnpaid.png
  docs/images/demos/revenueCommands/unmarkByIndex.png
  docs/images/demos/revenueCommands/unmarkall.png
  docs/images/demos/studentCommands/addStudent.png
  docs/images/demos/studentCommands/collatedCommands.png
  docs/images/demos/studentCommands/deleteByIndex.png
  docs/images/demos/studentCommands/deleteByName.png
  docs/images/demos/studentCommands/editStudent.png
  docs/images/demos/studentCommands/findStudent.png
  docs/images/demos/studentCommands/listStudents.png
  src/main/java/seedu/edulog/model/EduLog.java
  src/main/java/seedu/edulog/model/calendar/EdulogCalendar.java
  src/main/java/seedu/edulog/model/calendar/exceptions/LessonNotFoundException.java
  src/test/java/seedu/edulog/model/lesson/EdulogCalendarTest.java
  stylesheets/main.css
Labels: type.Bug, type.Documentation

#286 Update Command Summary
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#288 Update ug bugs
  docs/UserGuide.md
Labels: UG Bugs

#295 DG Architecture diagram fixes
  docs/DeveloperGuide.md
  docs/Testing.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/stylesheets/main.css
Labels: Archi/UML Bugs

#297 Update Developer Guide
  docs/DeveloperGuide.md
Labels: severity.High, priority.High, DG/ User Stories/ Cases Bugs

#298 Remove tutorials from Documentation
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: severity.High, priority.High, type.Documentation
